#!/bin/sh
set -e

apt-get update
apt-get install build-essential libtool autoconf automake gcc-multilib \
  ncurses-dev libexpat1-dev zlib1g-dev \
  gperf texinfo bison flex gettext cmake \
  gawk unzip curl \
  subversion git mercurial \
  nbd-client \
  vim zsh pv htop screen colordiff

cat > /etc/sudoers.d/nopasswd <<EOF
%sudo ALL=(ALL:ALL) NOPASSWD:ALL
EOF
chmod a=,ug+r /etc/sudoers.d/nopasswd
